services:
  backend:
    build: .
    env_file: .env
    network_mode: host
    volumes:
      - /etc/productivity-guard/:/etc/productivity-guard/
      - ./backend/config.yaml:/app/config.yaml:ro
      - pg-data:/data
    restart: unless-stopped

volumes:
  pg-data:
